# --------------------------------------------------
#  BASIC SITE INFO
# --------------------------------------------------
title: Ruishi Lin   # Main site title (appears in browser tab & RSS)
tagline: Here is personal website of Ruishi Lin.   # Strongly recommended for SEO & social cards

# TIP ── For local development you can comment out `url`
# and build with relative paths. In production you want this set.
url: Ruishi-Lin.github.io

# --------------------------------------------------
#  AUTHOR / PROFILE DATA
# --------------------------------------------------
owner:
  name: Ruishi Lin
  avatar: lrs.jpg
  # bio: Dream big, stay positive, work hard, and enjoy the journey.
  email: 13431733827@163.com
  # cv: https://caihanlin.com/file/CV-HanlinCAI.pdf

  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # facebook: 
  # lastfm:
  # tumblr:


# --------------------------------------------------
#  SEARCH-ENGINE VERIFICATION & ANALYTICS
# --------------------------------------------------
#google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"
# bing_verify: ""    # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# google_analytics: "G-XXXXXXX"                                 # GA-4 property ID


# --------------------------------------------------
#  TOP NAVIGATION BAR
#  `external: true` opens the link in a new tab.
# --------------------------------------------------
links:
  - title: About Me
    url: /
